name: main

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  ESPHOME_VERSION: 2024.6.6

jobs:
  build:
    name: build boneio-24-sw
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: build
        uses: esphome/build-action@v3.2.0
        id: esphome-build
        with:
          yaml_file: boneio-24-sw-07-737d50.yaml
          version: ${{ env.ESPHOME_VERSION }}
          cache: true

      - run: |
          mkdir output
          mv "${{ steps.esphome-build.outputs.name }}" output/

      - name: Get short SHA
        id: short_sha
        run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          commit: ${{ github.sha }}
          tag: ${{ steps.short_sha.outputs.short_sha }}
          makeLatest: true
          artifacts: output/*
